### ISSUE TITLE
DisplayPostInfo menu not showing

### ISSUE THREAD

**Issue by mimiffi** [BrokenEagle/JavaScripts#11]
I'm using firefox latest fresh install, with only userscript extension, DisplayMenuInfo menu at settings page is not showing up
![image](https://user-images.githubusercontent.com/122472228/211867842-d019e460-353d-4419-80e6-97a4073ad3a8.png)
Still works just fine, just need to bring it up with removing the css style

**Comment by BrokenEagle** [comment]
Fixed with 9eb78c2a543ad498da9b9ea2909a9caf4b1979e6 and deployed with 9bf9082a85758cc6923b38b1b2ced419e648daf7.

This was an issue affecting all userscripts, since Danbooru rolled out UI changes to the settings menu with https://github.com/danbooru/danbooru/commit/4a39e50ad026fb5d22e6045ba753350651c3c9a4.

**Note:** All userscripts from this repository must be updated to the latest version, or else the problem may still be present.
