### ISSUE TITLE
NTISAS - sometimes fails to find direct video link

### ISSUE THREAD

**Issue by bipface** [BrokenEagle/JavaScripts#5]
with some video (mp4) tweets, the _Download Originals_ list doesn't seem to be able to find the direct video link,
i suspect it occurs with tweets marked NSFW, based on a random set of examples i tested

an affected tweet (NSFW): <https://twitter.com/sakamotono114/status/1508027800971669505>
result:
![image](https://user-images.githubusercontent.com/24604367/161371845-05b3fe81-17a9-4df7-8fe5-488913b16a98.png)

here's a tweet which _does_ yield the video link (SFW): <https://twitter.com/nito210ni/status/1509139999006294016>
result:
![image](https://user-images.githubusercontent.com/24604367/161371976-2a313a7f-b546-4f5a-a140-ec5fa9dc3b6e.png)

observed with firefox v99 + violentmonkey v2.0.13.18,
also observed with chrome v102.0.4979.0 + tampermonkey v4.15

**Comment by BrokenEagle** [comment]
Here's what I got for the first tweet (NSFW) checking both Chrome and Firefox:

![image](https://user-images.githubusercontent.com/21149935/161449412-20859c77-3458-4dfe-a0f9-5be0a3622423.png)

- **Firefox 98.0.2**
    - **Violentmonkey 2.13.0**
- **Chrome 99.0.4844.51**
    - **Tampermonkey 4.15**

I discovered that the API scraper needs to be updated, since Twitter API has changed it's format (*once again*), so it wasn't able to use the API data normally provided by the XHR hook. I'm surprised though that the backup method of directly querying the API didn't work, as I was able to get it to work for both Chrome and Firefox.

https://github.com/BrokenEagle/JavaScripts/blob/0c027818579ba46b40f0f62ef0fa2c92a23f64ce/New_Twitter_Image_Searches_and_Stuff.user.js#L4411-L4415

I can fix the API scraper issue pretty easily, but I cannot fix why the backup method isn't working for you since I'm not experiencing an issue with that myself. Perhaps try to force the backup method yourself, and check the Tampermonkey/Violentmonkey background dev consoles for the network request it sends.

The network request should be:

- <https://api.twitter.com/1.1/statuses/show.json?id=1508027800971669505&tweet_mode=extended&trim_user=true>

If the video URL has been cached by NTISAS, it won't check either the API data or the network, so in that case, you would have to remove the cached data. You can use the following in the dev console when `JSPLib.debug.debug_console` has been set to `true` (*debug section at the end of the script*).

```javascript
JSPLib.lib.NTISAS.storage.removeData('video-1508027800971669505');
```

Another issue I noticed is that it shows 2 image URL links which are both the same. I'll look into that as well, but it'll be low-priority.

**Comment by BrokenEagle** [comment]
Alright, I pushed **Version 7.16** of NTISAS (72de571) which fixes the API scraping issue. I'll leave this issue open though due to the other issue of the backup method not working for some users.

**Comment by bipface** [comment]
one difference to note between violentmonkey and tampermonkey is that TM appears to be injecting the script directly into the page, while VM runs it as a content script (equivalent of `@inject-into content`).

the reason is twitter's CSP — tampermonkey circumvents the CSP by altering the `script-src` field of the CSP header in the response. violentmonkey doesn't have that 'feature', so it detects that it needs to use content script mode as a fallback.

the result is that the `XMLHttpRequest` hook doesn't appear to work at all in VM, because content scripts don't have access to the page's `window` (not even by `unsafeWindow`).

however, i haven't yet figured out why the `/show.json` requests are failing for me — always yields a 404 response

**Comment by BrokenEagle** [comment]
Are you logged in or are you browsing anonymously? When mine does the network request, it gets the data back just fine and doesn't 404. I believe that when you do the network request, it uses your own network credentials, for instance, I viewed the `/show.json` network request in the dev console, and its sending all of the following cookies:
- `_ga`
- `_gid`
- `auth_token`
- `ct0`
- `dnt`
- `guest_id`
- `guest_id_ads`
- `guest_id_marketing`
- `kdt`
- `personalization_id`
- `twid`

Unless you're logged in, you won't be able to view age-restricted content through the API. You'll just get a 404 response, like what you're experiencing.

<hr>

> the result is that the XMLHttpRequest hook doesn't appear to work at all in VM, because content scripts don't have access to the page's window (not even by unsafeWindow).

Are you sure about that? The hook appears to work just fine with me using VM.

![image](https://user-images.githubusercontent.com/21149935/161571179-c7f38f71-5fe5-4935-9a61-d2c42229a52c.png)

**Comment by bipface** [comment]
probably caused by
https://github.com/danbooru/danbooru/issues/5117

**Comment by BrokenEagle** [comment]
Yeah, you may be right. I'll try changing it over to use the GraphQL version to see if that makes a difference.

**Comment by BrokenEagle** [comment]
I pushed **Version 7.21** which adds in the ability to use GraphQL instead of Version 1.1 of the API. The switch for this is found on the settings menu under the **Network** tab at the bottom, called **Use GraphQL**.

Both methods worked for me under all circumstances, on both Chrome and Firefox, with both Tampermonkey and Violentmonkey.  I'm not experiencing the same problem, so I can't verify if it works or not for affected users.

**Comment by bipface** [comment]
excellent, that solution seems to be working perfectly
